// Code generated by protoc-gen-go. DO NOT EDIT.
// source: snapshot_recovery_response.proto

package protobuf

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type SnapshotRecoveryResponse struct {
	Term                 uint64   `protobuf:"varint,1,opt,name=Term,proto3" json:"Term,omitempty"`
	Success              bool     `protobuf:"varint,2,opt,name=Success,proto3" json:"Success,omitempty"`
	CommitIndex          uint64   `protobuf:"varint,3,opt,name=CommitIndex,proto3" json:"CommitIndex,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SnapshotRecoveryResponse) Reset()         { *m = SnapshotRecoveryResponse{} }
func (m *SnapshotRecoveryResponse) String() string { return proto.CompactTextString(m) }
func (*SnapshotRecoveryResponse) ProtoMessage()    {}
func (*SnapshotRecoveryResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_7557e26ca83826dc, []int{0}
}

func (m *SnapshotRecoveryResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SnapshotRecoveryResponse.Unmarshal(m, b)
}
func (m *SnapshotRecoveryResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SnapshotRecoveryResponse.Marshal(b, m, deterministic)
}
func (m *SnapshotRecoveryResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SnapshotRecoveryResponse.Merge(m, src)
}
func (m *SnapshotRecoveryResponse) XXX_Size() int {
	return xxx_messageInfo_SnapshotRecoveryResponse.Size(m)
}
func (m *SnapshotRecoveryResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_SnapshotRecoveryResponse.DiscardUnknown(m)
}

var xxx_messageInfo_SnapshotRecoveryResponse proto.InternalMessageInfo

func (m *SnapshotRecoveryResponse) GetTerm() uint64 {
	if m != nil {
		return m.Term
	}
	return 0
}

func (m *SnapshotRecoveryResponse) GetSuccess() bool {
	if m != nil {
		return m.Success
	}
	return false
}

func (m *SnapshotRecoveryResponse) GetCommitIndex() uint64 {
	if m != nil {
		return m.CommitIndex
	}
	return 0
}

func init() {
	proto.RegisterType((*SnapshotRecoveryResponse)(nil), "protobuf.SnapshotRecoveryResponse")
}

func init() { proto.RegisterFile("snapshot_recovery_response.proto", fileDescriptor_7557e26ca83826dc) }

var fileDescriptor_7557e26ca83826dc = []byte{
	// 140 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x52, 0x28, 0xce, 0x4b, 0x2c,
	0x28, 0xce, 0xc8, 0x2f, 0x89, 0x2f, 0x4a, 0x4d, 0xce, 0x2f, 0x4b, 0x2d, 0xaa, 0x8c, 0x2f, 0x4a,
	0x2d, 0x2e, 0xc8, 0xcf, 0x2b, 0x4e, 0xd5, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0xe2, 0x00, 0x53,
	0x49, 0xa5, 0x69, 0x4a, 0x59, 0x5c, 0x12, 0xc1, 0x50, 0xd5, 0x41, 0x50, 0xc5, 0x41, 0x50, 0xb5,
	0x42, 0x42, 0x5c, 0x2c, 0x21, 0xa9, 0x45, 0xb9, 0x12, 0x8c, 0x0a, 0x8c, 0x1a, 0x2c, 0x41, 0x60,
	0xb6, 0x90, 0x04, 0x17, 0x7b, 0x70, 0x69, 0x72, 0x72, 0x6a, 0x71, 0xb1, 0x04, 0x93, 0x02, 0xa3,
	0x06, 0x47, 0x10, 0x8c, 0x2b, 0xa4, 0xc0, 0xc5, 0xed, 0x9c, 0x9f, 0x9b, 0x9b, 0x59, 0xe2, 0x99,
	0x97, 0x92, 0x5a, 0x21, 0xc1, 0x0c, 0xd6, 0x84, 0x2c, 0x94, 0xc4, 0x06, 0xb6, 0xd5, 0x18, 0x10,
	0x00, 0x00, 0xff, 0xff, 0x77, 0xf7, 0x73, 0x20, 0xa0, 0x00, 0x00, 0x00,
}
